---
driver_config:
  iam_profile_name: ChefKitchenTestAws
  aws_ssh_key_id: chef-kitchen-test-aws

provisioner:
  name: chef_zero
  data_path: test/shared

platforms:
  - name: ubuntu-12.04
    driver_plugin: ec2

  - name: ubuntu-14.04
    driver_plugin: ec2


suites:
  - name: default
    run_list:
      - recipe[aws]

  - name: ebs_volume
    run_list:
      - recipe[aws_test::ebs_volume]
    attributes:
      aws_test:
        key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>

  - name: ebs_raid
    run_list:
      - recipe[aws_test::ebs_raid]
    attributes:
      aws_test:
        key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>

  - name: elastic_ip
    run_list:
      - recipe[aws_test::elastic_ip]
    attributes:
      aws_test:
        key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
        elastic_ip: <%= ENV['AWS_ELASTIC_IP'] %>

  - name: elb
    run_list:
      - recipe[aws_test::elb]
    attributes:
      aws_test:
        key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
        elb_name: <%= ENV['AWS_ELB_NAME'] %>

  - name: resource_tag
    run_list:
      - recipe[aws_test::resource_tag]
    attributes:
      aws_test:
        key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>

  - name: s3_file
    run_list:
      - recipe[aws_test::s3_file]
    attributes:
      aws_test:
        key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
        bucket: <%= ENV['AWS_S3_BUCKET'] || 'aws-test' %>
        s3key: <%= ENV['AWS_S3_KEY'] || 'an_file' %>

  - name: instance_monitoring
    run_list:
      - recipe[aws_test::instance_monitoring]
    attributes:
      aws_test:
        key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>

  - name: cfn_stack
    run_list:
      - recipe[aws_test::cfn_stack]

  - name: iam_user
    run_list:
      - recipe[aws_test::iam_user]

  - name: iam_group
    run_list:
      - recipe[aws_test::iam_group]

  - name: iam_policy
    run_list:
      - recipe[aws_test::iam_policy]

  - name: iam_role
    run_list:
      - recipe[aws_test::iam_role]

  - name: kinesis_stream
    run_list:
      - recipe[aws_test::kinesis_stream]

  - name: dynamodb_table_create
    run_list:
      - recipe[aws_test::dynamodb_table_create]

  - name: dynamodb_table_update
    run_list:
      - recipe[aws_test::dynamodb_table_update]
