---
driver_config:
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  availability_zone: <%= ENV['AWS_AVAILABILITY_ZONE'] %>

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.16.0

platforms:
- name: amazon-2014.09
  driver_plugin: ec2
  driver_config:
    image_id: ami-fccc6d94
    username: ec2-user
    ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
    flavor_id: t2.small

suites:
  - name: default
    run_list:
    - recipe[aws]

  - name: ebs_volume
    run_list:
    - recipe[aws_test::ebs_volume]
    attributes:
      aws_test:
        key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>

  - name: ebs_raid
    run_list:
    - recipe[aws_test::ebs_raid]
    attributes:
      aws_test:
        key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
